### ISSUE TITLE
expireAt not serialized properly

### ISSUE THREAD

**Issue by jkubrynski** [spring-projects/spring-session-data-mongodb#53]
### Actual behavior

Currently `MongoSession` is serialized inorrectly. The problem is in the `expireAt` field, which is serialized as `"expireAt" : [ "java.util.Date" , 1547418146965]`. It looks like it's due to `SecurityJackson2Modules.createWhitelistedDefaultTyping` invocation. In fact TTL index is not working as it cannot operate on array.

### Steps to reproduce

`new JacksonMongoSessionConverter().convert(new MongoSession));`

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-session-data-mongodb/commit/82cf365ba702d569013ce83940a6000933cfd3b6.

**Comment by mariuszs** [comment]
@gregturn  This applies also to 2.1.3 and is not fixed.  Any plan to backport fix to stable release?

`class java.util.ArrayList cannot be cast to class java.util.Date `
